name: Build and Deploy API

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/pet-research-api:${{ env.TAG }}
          ${{ secrets.DOCKER_USERNAME }}/pet-research-api:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /var/www/pet-research
          
          # Pull nova imagem
          docker pull ${{ secrets.DOCKER_USERNAME }}/pet-research-api:${{ env.TAG }}
          
          # Update .env com nova tag
          sed -i "s/TAG=.*/TAG=${{ env.TAG }}/" .env
          
          # Restart API
          docker compose up -d --no-deps api
          
          # Cleanup
          docker image prune -f
          
          # Health check
          sleep 15
          curl -f http://localhost/api/health || exit 1
